// PHASE 5: Scheduler.Application/Handlers/PdfReportHandler.cs
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Scheduler.Application.Dtos;
using Scheduler.Application.Interfaces.Handlers;
using Scheduler.Application.Interfaces.Services;

namespace Scheduler.Application.Handlers;

/// <summary>Handles PDF report generation tasks.</summary>
public class PdfReportHandler : ITaskHandler
{
    private readonly IReportGenerator _reportGenerator;
    private readonly IEmailService _emailService;
    private readonly ILogger<PdfReportHandler> _logger;

    /// <summary>Initializes a new instance of the <see cref="PdfReportHandler"/> class.</summary>
    public PdfReportHandler(IReportGenerator reportGenerator, IEmailService emailService, ILogger<PdfReportHandler> logger)
    {
        _reportGenerator = reportGenerator;
        _emailService = emailService;
        _logger = logger;
    }

    /// <inheritdoc />
    public async Task<TaskExecutionResultDto> ExecuteAsync(JobContextDto context, CancellationToken cancellationToken)
    {
        var request = new PdfReportRequestDto(context.PlantId + ":" + context.Variables.Count)
        {
            PlantId = context.PlantId,
            Variables = new List<string>(context.Variables),
            TimeRange = context.TimeRange
        };

        var report = await _reportGenerator.GenerateAsync(request, cancellationToken);
        var recipient = "ops@mintek.com";
        await _emailService.SendAsync(new EmailDeliveryDto
        {
            To = recipient,
            Subject = "Scheduled Report",
            Body = "Report generated by Job Scheduler.",
            Attachment = report
        }, cancellationToken);

        return new TaskExecutionResultDto(true)
        {
            Summary = $"Report generated: {report.FileName}, Email sent to {recipient}.",
            OutputLocation = report.FileName
        };
    }
}
